name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies (apt)
        run: sudo apt install -y libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching yarn packages
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generating `Bibata-Modern` symlinks
        run: cd svg && python link.py && cd ..
        continue-on-error: false

      - name: Generating `Bibata` Cursor Themes
        run: make
        continue-on-error: false

      - name: Compressing `Bibata-Modern` Unix Themes
        run: |
          tar -cvzf Bibata-Modern-DarkRed.tar.gz themes/Bibata-Modern-DarkRed
          tar -cvzf Bibata-Modern-DodgerBlue.tar.gz themes/Bibata-Modern-DodgerBlue
          tar -cvzf Bibata-Modern-Pink.tar.gz themes/Bibata-Modern-Pink
          tar -cvzf Bibata-Modern-Turquoise.tar.gz themes/Bibata-Modern-Turquoise

      - name: Uploading `Bibata-Modern-DarkRed` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-DarkRed
          path: Bibata-Modern-DarkRed.tar.gz

      - name: Uploading `Bibata-Modern-DarkRed` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-DarkRed-Windows
          path: themes/Bibata-Modern-DarkRed-Windows/*

      - name: Uploading `Bibata-Modern-DodgerBlue` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-DodgerBlue
          path: Bibata-Modern-DodgerBlue.tar.gz

      - name: Uploading `Bibata-Modern-DodgerBlue` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-DodgerBlue-Windows
          path: themes/Bibata-Modern-DodgerBlue-Windows/*

      - name: Uploading `Bibata-Modern-Pink` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Pink
          path: Bibata-Modern-Pink.tar.gz

      - name: Uploading `Bibata-Modern-Pink` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Pink-Windows
          path: themes/Bibata-Modern-Pink-Windows/*

      - name: Uploading `Bibata-Modern-Turquoise` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Turquoise
          path: Bibata-Modern-Turquoise.tar.gz

      - name: Uploading `Bibata-Modern-Turquoise` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Turquoise-Windows
          path: themes/Bibata-Modern-Turquoise-Windows/*

      - name: Compressing `Bibata-Original` Unix Themes
        run: |
          tar -cvzf Bibata-Original-DarkRed.tar.gz themes/Bibata-Original-DarkRed
          tar -cvzf Bibata-Original-DodgerBlue.tar.gz themes/Bibata-Original-DodgerBlue
          tar -cvzf Bibata-Original-Pink.tar.gz themes/Bibata-Original-Pink
          tar -cvzf Bibata-Original-Turquoise.tar.gz themes/Bibata-Original-Turquoise

      - name: Uploading `Bibata-Original-DarkRed` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-DarkRed
          path: Bibata-Original-DarkRed.tar.gz

      - name: Uploading `Bibata-Original-DarkRed` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-DarkRed-Windows
          path: themes/Bibata-Original-DarkRed-Windows/*

      - name: Uploading `Bibata-Original-DodgerBlue` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-DodgerBlue
          path: Bibata-Original-DodgerBlue.tar.gz

      - name: Uploading `Bibata-Original-DodgerBlue` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-DodgerBlue-Windows
          path: themes/Bibata-Original-DodgerBlue-Windows/*

      - name: Uploading `Bibata-Original-Pink` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Pink
          path: Bibata-Original-Pink.tar.gz

      - name: Uploading `Bibata-Original-Pink` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Pink-Windows
          path: themes/Bibata-Original-Pink-Windows/*

      - name: Uploading `Bibata-Original-Turquoise` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Turquoise
          path: Bibata-Original-Turquoise.tar.gz

      - name: Uploading `Bibata-Original-Turquoise` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Turquoise-Windows
          path: themes/Bibata-Original-Turquoise-Windows/*

      - name: Uploading `Bibata` bitmaps artifact
        uses: actions/upload-artifact@v2
        with:
          name: bitmaps
          path: bitmaps/*
